package loteriamexicanamultiplayer;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.net.Socket;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Angelica Figueroa Muñiz
 */
public class InformacionCliente extends javax.swing.JFrame {
    
    private int port = 0000;
    private String ip = "";
    private String name = "";
    private Socket cliente = null;
    BufferedReader in = null;
    PrintWriter out = null;
    BufferedReader teclado = null;
    ObjectInputStream entradaObjetos = null;
    ObjectOutputStream salidaObjetos = null;

    public int getPort() {
        return port;
    }

    public String getIp() {
        return ip;
    }

    public String getName() {
        return name;
    }    
    

    /**
     * Creates new form InformacionCliente
     */
    public InformacionCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        puerto = new javax.swing.JLabel();
        IP = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        puertoText = new javax.swing.JTextField();
        IPText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo jugador");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(570, 350));
        setMinimumSize(new java.awt.Dimension(510, 187));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 90, 110, 40);

        nombre.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        nombre.setText("Nombre:");
        getContentPane().add(nombre);
        nombre.setBounds(35, 41, 89, 25);

        puerto.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        puerto.setText("Puerto:");
        getContentPane().add(puerto);
        puerto.setBounds(296, 41, 73, 25);

        IP.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        IP.setText("IP:");
        getContentPane().add(IP);
        IP.setBounds(40, 80, 30, 40);

        nombreText.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });
        getContentPane().add(nombreText);
        nombreText.setBounds(130, 38, 149, 40);

        puertoText.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        getContentPane().add(puertoText);
        puertoText.setBounds(375, 38, 105, 40);

        IPText.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        getContentPane().add(IPText);
        IPText.setBounds(80, 90, 270, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\harry\\OneDrive\\Fotos\\infoClient.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-160, 0, 672, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        port = Integer.parseInt(puertoText.getText());
        ip = IPText.getText();
        name = nombreText.getText();
        //System.out.println(puertoText.getText());
        //System.out.println(IPText.getText());
        //System.out.println(nombreText.getText());
        //setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IP;
    private javax.swing.JTextField IPText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel puerto;
    private javax.swing.JTextField puertoText;
    // End of variables declaration//GEN-END:variables
}
