/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loteriamexicanamultiplayer;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import misClases.Picture;

/**
 *
 * @author Angelica Figueroa
 */
public class TablaGrafica extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form verTabla
     */
        private static Bonche bonche;
        private Tabla tabla = new Tabla();
        private String numero = Integer.toString(tabla.getNumeroDeTabla());
        private ArrayList <String> marcadas = new ArrayList <String> ();
        static int count = 0;
        private Griton griton;
        private String presionoLoteria = "NO";
        
        
    public TablaGrafica(Griton griton) {
        initComponents();
        this.griton = griton;
    }
    
    public ArrayList<String> getMarcadas() {
        return marcadas;
    }

    public void actualizarCarta(Image imagen) {
        jLabel3.setIcon(new ImageIcon(imagen));
      
    }
    
    public void actualizarFrase(String f){
        frase.setText("<html>\t" + f + "</html>");
        
    }
    
    public void ponerNombre(String nombre){
        jLabel6.setText(jLabel6.getText() + " " + nombre);
    }

    public String getPresionoLoteria() {
        return presionoLoteria;
    }

    public void setPresionoLoteria(String presionoLoteria) {
        this.presionoLoteria = presionoLoteria;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ganador = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backImage1 = new javax.swing.JLabel();
        perdedor = new javax.swing.JDialog();
        perdedorText = new javax.swing.JLabel();
        perdedorText1 = new javax.swing.JLabel();
        perdedorText2 = new javax.swing.JLabel();
        perdedorText3 = new javax.swing.JLabel();
        suerteText = new javax.swing.JLabel();
        perdedorText4 = new javax.swing.JLabel();
        perdedorText5 = new javax.swing.JLabel();
        perdedorText6 = new javax.swing.JLabel();
        perdedorText8 = new javax.swing.JLabel();
        backImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loteria = new javax.swing.JButton();
        frase = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        ganador.setMinimumSize(new java.awt.Dimension(625, 422));

        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Futura PT Medium", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ha ganado la partida");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(190, 290, 423, 49);

        jLabel4.setFont(new java.awt.Font("Argon PERSONAL", 0, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Felicidades!");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 190, 499, 151);
        jPanel2.add(backImage1);
        backImage1.setBounds(0, -40, 630, 430);

        javax.swing.GroupLayout ganadorLayout = new javax.swing.GroupLayout(ganador.getContentPane());
        ganador.getContentPane().setLayout(ganadorLayout);
        ganadorLayout.setHorizontalGroup(
            ganadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ganadorLayout.setVerticalGroup(
            ganadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        perdedor.setTitle("Perdedor");
        perdedor.setMinimumSize(new java.awt.Dimension(625, 422));
        perdedor.getContentPane().setLayout(null);

        perdedorText.setFont(new java.awt.Font("Argon PERSONAL", 0, 95)); // NOI18N
        perdedorText.setForeground(new java.awt.Color(46, 77, 255));
        perdedorText.setText("P");
        perdedorText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        perdedor.getContentPane().add(perdedorText);
        perdedorText.setBounds(100, 130, 70, 170);

        perdedorText1.setFont(new java.awt.Font("Argon PERSONAL", 0, 95)); // NOI18N
        perdedorText1.setForeground(new java.awt.Color(204, 102, 255));
        perdedorText1.setText("E");
        perdedorText1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        perdedor.getContentPane().add(perdedorText1);
        perdedorText1.setBounds(150, 180, 50, 151);

        perdedorText2.setFont(new java.awt.Font("Argon PERSONAL", 0, 95)); // NOI18N
        perdedorText2.setForeground(new java.awt.Color(226, 89, 127));
        perdedorText2.setText("R");
        perdedorText2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        perdedor.getContentPane().add(perdedorText2);
        perdedorText2.setBounds(520, 220, 60, 151);

        perdedorText3.setFont(new java.awt.Font("Argon PERSONAL", 0, 95)); // NOI18N
        perdedorText3.setForeground(new java.awt.Color(240, 177, 54));
        perdedorText3.setText("D");
        perdedorText3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        perdedor.getContentPane().add(perdedorText3);
        perdedorText3.setBounds(390, 150, 70, 160);

        suerteText.setFont(new java.awt.Font("Futura PT Medium", 0, 60)); // NOI18N
        suerteText.setForeground(new java.awt.Color(255, 255, 255));
        suerteText.setText("nice try...");
        perdedor.getContentPane().add(suerteText);
        suerteText.setBounds(20, 40, 240, 61);

        perdedorText4.setFont(new java.awt.Font("Argon PERSONAL", 0, 95)); // NOI18N
        perdedorText4.setForeground(new java.awt.Color(237, 195, 31));
        perdedorText4.setText("E");
        perdedorText4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        perdedor.getContentPane().add(perdedorText4);
        perdedorText4.setBounds(340, 170, 50, 151);

        perdedorText5.setFont(new java.awt.Font("Argon PERSONAL", 0, 95)); // NOI18N
        perdedorText5.setForeground(new java.awt.Color(201, 59, 46));
        perdedorText5.setText("O");
        perdedorText5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        perdedor.getContentPane().add(perdedorText5);
        perdedorText5.setBounds(450, 180, 70, 170);

        perdedorText6.setFont(new java.awt.Font("Argon PERSONAL", 0, 95)); // NOI18N
        perdedorText6.setForeground(new java.awt.Color(244, 243, 96));
        perdedorText6.setText("D");
        perdedorText6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        perdedor.getContentPane().add(perdedorText6);
        perdedorText6.setBounds(270, 190, 80, 160);

        perdedorText8.setFont(new java.awt.Font("Argon PERSONAL", 0, 95)); // NOI18N
        perdedorText8.setForeground(new java.awt.Color(123, 225, 86));
        perdedorText8.setText("R");
        perdedorText8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        perdedor.getContentPane().add(perdedorText8);
        perdedorText8.setBounds(210, 210, 60, 151);
        perdedor.getContentPane().add(backImage);
        backImage.setBounds(0, -40, 630, 430);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loteria Mexicana");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(250, 250, 235));

        jButton1.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton1.setForeground(new java.awt.Color(8, 225, 182));
        jButton1.setIcon(new ImageIcon(tabla.getImagen(0)));
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton2.setForeground(new java.awt.Color(8, 225, 182));
        jButton2.setIcon(new ImageIcon(tabla.getImagen(1)));
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton3.setForeground(new java.awt.Color(8, 225, 182));
        jButton3.setIcon(new ImageIcon(tabla.getImagen(2)));
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton4.setForeground(new java.awt.Color(8, 225, 182));
        jButton4.setIcon(new ImageIcon(tabla.getImagen(3)));
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton5.setForeground(new java.awt.Color(8, 225, 182));
        jButton5.setIcon(new ImageIcon(tabla.getImagen(4)));
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton6.setForeground(new java.awt.Color(8, 225, 182));
        jButton6.setIcon(new ImageIcon(tabla.getImagen(5)));
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton7.setForeground(new java.awt.Color(8, 225, 182));
        jButton7.setIcon(new ImageIcon(tabla.getImagen(6)));
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton8.setForeground(new java.awt.Color(8, 225, 182));
        jButton8.setIcon(new ImageIcon(tabla.getImagen(7)));
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton10.setForeground(new java.awt.Color(8, 225, 182));
        jButton10.setIcon(new ImageIcon(tabla.getImagen(9)));
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton11.setForeground(new java.awt.Color(8, 225, 182));
        jButton11.setIcon(new ImageIcon(tabla.getImagen(10)));
        jButton11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton12.setForeground(new java.awt.Color(8, 225, 182));
        jButton12.setIcon(new ImageIcon(tabla.getImagen(11)));
        jButton12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton13.setForeground(new java.awt.Color(8, 225, 182));
        jButton13.setIcon(new ImageIcon(tabla.getImagen(12)));
        jButton13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton14.setForeground(new java.awt.Color(8, 225, 182));
        jButton14.setIcon(new ImageIcon(tabla.getImagen(13)));
        jButton14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton15.setForeground(new java.awt.Color(8, 225, 182));
        jButton15.setIcon(new ImageIcon(tabla.getImagen(14)));
        jButton15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton16.setForeground(new java.awt.Color(8, 225, 182));
        jButton16.setIcon(new ImageIcon(tabla.getImagen(15)));
        jButton16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("TABLA " + numero);

        jButton9.setFont(new java.awt.Font("Arial", 1, 94)); // NOI18N
        jButton9.setForeground(new java.awt.Color(8, 225, 182));
        jButton9.setIcon(new ImageIcon(tabla.getImagen(8)));
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 28)); // NOI18N
        jLabel1.setText("LOTERIA");

        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 222, 189), 3, true));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        loteria.setFont(new java.awt.Font("Malgun Gothic", 1, 26)); // NOI18N
        loteria.setText("¡Loteria!");
        loteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loteriaActionPerformed(evt);
            }
        });

        frase.setBackground(new java.awt.Color(0, 204, 255));
        frase.setFont(new java.awt.Font("Tw Cen MT", 0, 26)); // NOI18N
        frase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frase.setAlignmentX(0.5F);
        frase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        frase.setIconTextGap(0);

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 22)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(loteria)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(frase, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setText("X");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton1.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(0).getNombre());
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jButton9.setText("X");
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton9.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(8).getNombre());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setText("X");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton2.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(1).getNombre());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.setText("X");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton3.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(2).getNombre());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setText("X");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton4.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(3).getNombre());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jButton5.setText("X");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton5.setEnabled(false);
       marcadas.add(tabla.getPersonajes().get(4).getNombre());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton6.setText("X");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton6.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(5).getNombre());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton7.setText("X");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton7.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(6).getNombre());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jButton8.setText("X");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton8.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(8).getNombre());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jButton10.setText("X");
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton10.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(9).getNombre());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jButton11.setText("X");
        jButton11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton11.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(10).getNombre());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jButton12.setText("X");
        jButton12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton12.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(11).getNombre());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jButton13.setText("X");
        jButton13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton13.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(12).getNombre());
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jButton14.setText("X");
        jButton14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton14.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(13).getNombre());
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jButton15.setText("X");
        jButton15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton15.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(14).getNombre());
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        jButton16.setText("X");
        jButton16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 253, 203), 3, true));
        jButton16.setEnabled(false);
        marcadas.add(tabla.getPersonajes().get(15).getNombre());
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
//        Carta c = bonche.obtenerCarta();
//        sacadas.add(c.getPersonaje());
//        Picture p = new Picture(c.getPersonaje().getImagen());
//        Image img = p.getImage();
//        Image newI = img.getScaledInstance( jLabel3.getWidth(), jLabel3.getHeight(),  java.awt.Image.SCALE_SMOOTH ) ;
//        jLabel3.setIcon(new ImageIcon(newI));

    }//GEN-LAST:event_jLabel3MouseClicked

    private void loteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loteriaActionPerformed
        // TODO add your handling code here:
        //timer.stop();
        //System.out.println(marcadas);
        //System.out.println(sacadas);
//        if (griton.comprobarLoteria(marcadas)) {
//            ganador.setVisible(true);
//        } else {
//            perdedor.setVisible(true);
//        }
        presionoLoteria = "SI";

    }//GEN-LAST:event_loteriaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TablaGrafica(griton).setVisible(true);
                    

   
            }
        });

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backImage;
    private javax.swing.JLabel backImage1;
    private javax.swing.JLabel frase;
    private javax.swing.JDialog ganador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loteria;
    private javax.swing.JDialog perdedor;
    private javax.swing.JLabel perdedorText;
    private javax.swing.JLabel perdedorText1;
    private javax.swing.JLabel perdedorText2;
    private javax.swing.JLabel perdedorText3;
    private javax.swing.JLabel perdedorText4;
    private javax.swing.JLabel perdedorText5;
    private javax.swing.JLabel perdedorText6;
    private javax.swing.JLabel perdedorText8;
    private javax.swing.JLabel suerteText;
    // End of variables declaration//GEN-END:variables
}
